[tool.poetry]
name = "sample-explorer"
version = "0.1.0"
description = ""
authors = ["Marek Wiewiorski <marek@mwicat.com>"]
readme = "README.md"
packages = [{include = "sample_explorer", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
PyQt5 = "^5"

[tool.poetry.scripts]
samplexplore = "sample_explorer.app:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
